type FileRemover = { delete: (key: string) => Promise<unknown> };

// Called after the metadata transaction, and retried by the server worker.
// Object keys are generated by the application, never accepted from clients.
export async function cleanDeletedFile(
  db: D1Database,
  files: FileRemover,
  operationId: string,
  now = Date.now(),
) {
  const job = await db
    .prepare(
      'SELECT r2_key AS key, attempts FROM file_deletion_jobs WHERE operation_id = ?',
    )
    .bind(operationId)
    .first<{ key: string; attempts: number }>();
  if (!job) return true;
  try {
    let timer: ReturnType<typeof setTimeout> | undefined;
    try {
      await Promise.race([
        files.delete(job.key),
        new Promise<never>((_, reject) => {
          timer = setTimeout(
            () => reject(new Error('File cleanup timeout')),
            10_000,
          );
        }),
      ]);
    } finally {
      if (timer) clearTimeout(timer);
    }
    await db
      .prepare(
        'DELETE FROM file_deletion_jobs WHERE operation_id = ? AND r2_key = ?',
      )
      .bind(operationId, job.key)
      .run();
    return true;
  } catch {
    if (job.attempts === 0 || (job.attempts + 1) % 10 === 0)
      console.warn(
        'Private file cleanup will retry; storage requires attention if this persists.',
      );
    await db
      .prepare(`UPDATE file_deletion_jobs SET attempts = attempts + 1,
      next_attempt_at = ? WHERE operation_id = ?`)
      .bind(now + 60_000, operationId)
      .run();
    return false;
  }
}

export async function processFileDeletions(
  db: D1Database,
  files: FileRemover,
  now = Date.now(),
) {
  const jobs = await db
    .prepare(`SELECT operation_id AS id FROM file_deletion_jobs
    WHERE next_attempt_at <= ? ORDER BY next_attempt_at LIMIT 5`)
    .bind(now)
    .all<{ id: string }>();
  for (const job of jobs.results)
    await cleanDeletedFile(db, files, job.id, now);
}
