// Verified public product references, checked 2026-09-08.
// See docs/catalog-regional.md for coverage and market semantics.
export type RegionalCatalogCode = {
  model: string;
  color: string;
  memory: string;
  value: string;
  market: string;
  partNumber: string;
  sources: readonly string[];
};

export const REGIONAL_CATALOG_CODES: readonly RegionalCatalogCode[] = [
  {
    model: 'iPhone 17',
    color: 'Preto',
    memory: '256 GB',
    value: '195950643442',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MG6J4HN/A',
    sources: [
      'https://inspireonline.in/products/iphone-17-mg6j4hn-a',
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-17-256gb-black-sim-1019166',
      'https://iplanet.one/products/iphone-17-mg6j4hn-a',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Branco',
    memory: '256 GB',
    value: '195950643640',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MG6K4HN/A',
    sources: [
      'https://inspireonline.in/products/iphone-17-mg6k4hn-a',
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-17-256gb-white-sim-1019172',
      'https://nexus247.iplanet.one/products/iphone-17-mg6k4hn-a',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Azul-névoa',
    memory: '256 GB',
    value: '195950643848',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MG6L4HN/A',
    sources: [
      'https://www.spectrum-international.fr/fr/boutique/1866923/apple-iphone-17-256gb-mist-blue-indian-spec/',
      'https://www.shoppingchina.com.py/producto/1019170',
      'https://indigo.iplanet.one/products/iphone-17-mg6l4hn-a',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Lavanda',
    memory: '256 GB',
    value: '195950644043',
    market: 'Índia',
    partNumber: 'MG6M4HN/A',
    sources: ['https://dcs.dk/da/p/1003824080'],
  },
  {
    model: 'iPhone 17',
    color: 'Sálvia',
    memory: '256 GB',
    value: '195950644241',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MG6N4HN/A',
    sources: [
      'https://inspireonline.in/products/iphone-17-mg6n4hn-a',
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-17-256gb-sage-sim-1019168',
      'https://iplanet.one/products/iphone-17-mg6n4hn-a',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Preto',
    memory: '512 GB',
    value: '195950644449',
    market: 'Índia',
    partNumber: 'MG6P4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17-mg6p4hn-a'],
  },
  {
    model: 'iPhone 17',
    color: 'Branco',
    memory: '512 GB',
    value: '195950644647',
    market: 'Índia',
    partNumber: 'MG6Q4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17-mg6q4hn-a'],
  },
  {
    model: 'iPhone 17',
    color: 'Azul-névoa',
    memory: '512 GB',
    value: '195950644845',
    market: 'Índia',
    partNumber: 'MG6T4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17-mg6t4hn-a'],
  },
  {
    model: 'iPhone 17',
    color: 'Lavanda',
    memory: '512 GB',
    value: '195950645040',
    market: 'Índia',
    partNumber: 'MG6U4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17-mg6u4hn-a'],
  },
  {
    model: 'iPhone 17',
    color: 'Sálvia',
    memory: '512 GB',
    value: '195950645248',
    market: 'Índia',
    partNumber: 'MG6V4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17-mg6v4hn-a'],
  },
  {
    model: 'iPhone 17',
    color: 'Preto',
    memory: '256 GB',
    value: '195950643428',
    market: 'Brasil',
    partNumber: 'MG6J4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--256gb--preto--tela-de-6-3---5g-e-camera-de-48mp-aemg6j4brapto_prd-167316/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Branco',
    memory: '256 GB',
    value: '195950643626',
    market: 'Brasil',
    partNumber: 'MG6K4BR/A',
    sources: [
      'https://empresas.fastshop.com.br/iphone-17-apple--256gb--branco--tela-de-6-3---5g-e-camera-de-48mp-aemg6k4brabco_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Azul-névoa',
    memory: '256 GB',
    value: '195950643824',
    market: 'Brasil',
    partNumber: 'MG6L4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--256gb--azul-nevoa--tela-de-6-3---5g-e-camera-de-48mp-aemg6l4braazl_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Lavanda',
    memory: '256 GB',
    value: '195950644029',
    market: 'Brasil',
    partNumber: 'MG6M4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--256gb--lavanda--tela-de-6-3---5g-e-camera-de-48mp-aemg6m4brarxo_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Sálvia',
    memory: '256 GB',
    value: '195950644227',
    market: 'Brasil',
    partNumber: 'MG6N4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--256gb--salvia--tela-de-6-3---5g-e-camera-de-48mp-aemg6n4bravrd_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Preto',
    memory: '512 GB',
    value: '195950644425',
    market: 'Brasil',
    partNumber: 'MG6P4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--512gb--preto--tela-de-6-3---5g-e-camera-de-48mp-aemg6p4brapto_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Branco',
    memory: '512 GB',
    value: '195950644623',
    market: 'Brasil',
    partNumber: 'MG6Q4BR/A',
    sources: [
      'https://empresas.fastshop.com.br/iphone-17-apple--512gb--branco--tela-de-6-3---5g-e-camera-de-48mp-aemg6q4brabco_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Azul-névoa',
    memory: '512 GB',
    value: '195950644821',
    market: 'Brasil',
    partNumber: 'MG6T4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--512gb--azul-nevoa--tela-de-6-3---5g-e-camera-de-48mp-aemg6t4braazl_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Lavanda',
    memory: '512 GB',
    value: '195950645026',
    market: 'Brasil',
    partNumber: 'MG6U4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--512gb--lavanda--tela-de-6-3---5g-e-camera-de-48mp-aemg6u4brarxo_prd/p',
    ],
  },
  {
    model: 'iPhone 17',
    color: 'Sálvia',
    memory: '512 GB',
    value: '195950645224',
    market: 'Brasil',
    partNumber: 'MG6V4BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-17-apple--512gb--salvia--tela-de-6-3---5g-e-camera-de-48mp-aemg6v4bravrd_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Preto',
    memory: '128 GB',
    value: '195949821837',
    market: 'Índia',
    partNumber: 'MYE73HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-mye73hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Branco',
    memory: '128 GB',
    value: '195949822018',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MYE93HN/A',
    sources: [
      'https://inspireonline.in/products/iphone-16-mye93hn-a',
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-16-a3081-128gb-white-sim-948624',
      'https://iplanet.one/products/iphone-16-128gb-white',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Rosa',
    memory: '128 GB',
    value: '195949822193',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MYEA3HN/A',
    sources: [
      'https://inspireonline.in/products/iphone-16-myea3hn-a',
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-16-a3287-128gb-pink-sim-948625',
      'https://iplanet.one/products/iphone-16-myea3hn-a',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Ultramarino',
    memory: '128 GB',
    value: '195949822377',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MYEC3HN/A',
    sources: [
      'https://inspireonline.in/products/iphone-16-myec3hn-a',
      'https://www.shoppingchina.com.py/producto/950216',
      'https://iplanet.one/products/iphone-16-128gb-ultramarine',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Verde-azulado',
    memory: '128 GB',
    value: '195949822551',
    market: 'Índia · vendido no Paraguai',
    partNumber: 'MYED3HN/A',
    sources: [
      'https://indigo.iplanet.one/products/iphone-16-myed3hn-a',
      'https://www.shoppingchina.com.py/producto/948626',
      'https://www.cenoteka.rs/p/apple-iphone-16-8128gb-teal-myed3hna-akcija-cena/',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Preto',
    memory: '256 GB',
    value: '195949822735',
    market: 'Índia',
    partNumber: 'MYEE3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myee3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Branco',
    memory: '256 GB',
    value: '195949822919',
    market: 'Índia',
    partNumber: 'MYEF3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myef3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Rosa',
    memory: '256 GB',
    value: '195949823091',
    market: 'Índia',
    partNumber: 'MYEG3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myeg3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Ultramarino',
    memory: '256 GB',
    value: '195949823275',
    market: 'Índia',
    partNumber: 'MYEH3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myeh3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Verde-azulado',
    memory: '256 GB',
    value: '195949823459',
    market: 'Índia',
    partNumber: 'MYEJ3HN/A',
    sources: ['https://indigo.iplanet.one/products/iphone-16-myej3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Preto',
    memory: '512 GB',
    value: '195949823633',
    market: 'Índia',
    partNumber: 'MYEK3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myek3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Branco',
    memory: '512 GB',
    value: '195949823817',
    market: 'Índia',
    partNumber: 'MYEP3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myep3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Rosa',
    memory: '512 GB',
    value: '195949823992',
    market: 'Índia',
    partNumber: 'MYEQ3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myeq3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Ultramarino',
    memory: '512 GB',
    value: '195949824173',
    market: 'Índia',
    partNumber: 'MYER3HN/A',
    sources: ['https://iplanet.one/products/iphone-16-myer3hn-a'],
  },
  {
    model: 'iPhone 16',
    color: 'Verde-azulado',
    memory: '512 GB',
    value: '195949824357',
    market: 'Índia',
    partNumber: 'MYEU3HN/A',
    sources: ['https://inspireonline.in/products/iphone-16-myeu3hn-a'],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Prateado',
    memory: '256 GB',
    value: '195950627107',
    market: 'Índia',
    partNumber: 'MG8G4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8g4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Laranja-cósmico',
    memory: '256 GB',
    value: '195950627305',
    market: 'Índia',
    partNumber: 'MG8H4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8h4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Azul-intenso',
    memory: '256 GB',
    value: '195950627503',
    market: 'Índia',
    partNumber: 'MG8J4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8j4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Prateado',
    memory: '512 GB',
    value: '195950627701',
    market: 'Índia',
    partNumber: 'MG8K4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8k4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Laranja-cósmico',
    memory: '512 GB',
    value: '195950627909',
    market: 'Índia',
    partNumber: 'MG8M4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8m4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Azul-intenso',
    memory: '512 GB',
    value: '195950628104',
    market: 'Índia',
    partNumber: 'MG8N4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8n4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Prateado',
    memory: '1 TB',
    value: '195950628302',
    market: 'Índia',
    partNumber: 'MG8P4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8p4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Laranja-cósmico',
    memory: '1 TB',
    value: '195950628500',
    market: 'Índia',
    partNumber: 'MG8Q4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8q4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Azul-intenso',
    memory: '1 TB',
    value: '195950628708',
    market: 'Índia',
    partNumber: 'MG8R4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg8r4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Prateado',
    memory: '256 GB',
    value: '195950638752',
    market: 'Índia',
    partNumber: 'MFYM4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfym4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Laranja-cósmico',
    memory: '256 GB',
    value: '195950638950',
    market: 'Índia',
    partNumber: 'MFYN4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyn4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Azul-intenso',
    memory: '256 GB',
    value: '195950639155',
    market: 'Índia',
    partNumber: 'MFYP4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyp4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Prateado',
    memory: '512 GB',
    value: '195950639353',
    market: 'Índia',
    partNumber: 'MFYQ4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyq4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Laranja-cósmico',
    memory: '512 GB',
    value: '195950639551',
    market: 'Índia',
    partNumber: 'MFYT4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyt4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Azul-intenso',
    memory: '512 GB',
    value: '195950639759',
    market: 'Índia',
    partNumber: 'MFYU4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyu4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Prateado',
    memory: '1 TB',
    value: '195950639957',
    market: 'Índia',
    partNumber: 'MFYV4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyv4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Laranja-cósmico',
    memory: '1 TB',
    value: '195950640151',
    market: 'Índia',
    partNumber: 'MFYW4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyw4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Azul-intenso',
    memory: '1 TB',
    value: '195950640359',
    market: 'Índia',
    partNumber: 'MFYX4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyx4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Prateado',
    memory: '2 TB',
    value: '195950640557',
    market: 'Índia',
    partNumber: 'MFYY4HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mfyy4hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Laranja-cósmico',
    memory: '2 TB',
    value: '195950640755',
    market: 'Índia',
    partNumber: 'MG004HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg004hn-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Azul-intenso',
    memory: '2 TB',
    value: '195950640953',
    market: 'Índia',
    partNumber: 'MG014HN/A',
    sources: [
      'https://www.imagineonline.store/products/iphone-17-pro-mg014hn-a',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Preto',
    memory: '128 GB',
    value: '195949824951',
    market: 'Brasil',
    partNumber: 'MYE73BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-16-apple--128gb--preto--tela-de-6-1---5g-e-camera-de-48mp-aemye73brapto_prd-66785/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Branco',
    memory: '128 GB',
    value: '195949824968',
    market: 'Brasil',
    partNumber: 'MYE93BR/A',
    sources: [
      'https://secure3.fastshop.com.br/iphone-16-apple--128gb--branco--tela-de-6-1---5g-e-camera-de-48mp-aemye93brabco_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Rosa',
    memory: '128 GB',
    value: '195949824975',
    market: 'Brasil',
    partNumber: 'MYEA3BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-16-apple--128gb--rosa--tela-de-6-1---5g-e-camera-de-48mp-aemyea3brarsa_prd-66787/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Ultramarino',
    memory: '128 GB',
    value: '195949824982',
    market: 'Brasil',
    partNumber: 'MYEC3BR/A',
    sources: [
      'https://empresas.fastshop.com.br/iphone-16-apple--128gb--ultramarino--tela-de-6-1---5g-e-camera-de-48mp-aemyec3braazl_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Verde-azulado',
    memory: '128 GB',
    value: '195949824999',
    market: 'Brasil',
    partNumber: 'MYED3BR/A',
    sources: [
      'https://secure3.fastshop.com.br/iphone-16-apple--128gb--verde-acinzentado--tela-de-6-1---5g-e-camera-de-48mp-aemyed3bravrd_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Preto',
    memory: '256 GB',
    value: '195949825002',
    market: 'Brasil',
    partNumber: 'MYEE3BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-16-apple--256gb--preto--tela-de-6-1---5g-e-camera-de-48mp-aemyee3brapto_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Branco',
    memory: '256 GB',
    value: '195949825019',
    market: 'Brasil',
    partNumber: 'MYEF3BR/A',
    sources: [
      'https://familyandfriendsb2b.fastshop.com.br/iphone-16-apple--256gb--branco--tela-de-6-1---5g-e-camera-de-48mp-aemyef3brabco_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Rosa',
    memory: '256 GB',
    value: '195949825026',
    market: 'Brasil',
    partNumber: 'MYEG3BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-16-apple--256gb--rosa--tela-de-6-1---5g-e-camera-de-48mp-aemyeg3brarsa_prd/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Ultramarino',
    memory: '256 GB',
    value: '195949825033',
    market: 'Brasil',
    partNumber: 'MYEH3BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-16-apple--256gb--ultramarino--tela-de-6-1---5g-e-camera-de-48mp-aemyeh3braazl_prd-66793/p',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Verde-azulado',
    memory: '256 GB',
    value: '195949825040',
    market: 'Brasil',
    partNumber: 'MYEJ3BR/A',
    sources: [
      'https://site.fastshop.com.br/iphone-16-apple--256gb--verde-acinzentado--tela-de-6-1---5g-e-camera-de-48mp-aemyej3bravrd_prd-66794/p',
    ],
  },
  {
    model: 'iPhone 16e',
    color: 'Preto',
    memory: '128 GB',
    value: '195950051094',
    market: 'Índia',
    partNumber: 'MD1Q4HN/A',
    sources: ['https://inspireonline.in/products/iphone-16e-md1q4hn-a'],
  },
  {
    model: 'iPhone 16e',
    color: 'Branco',
    memory: '128 GB',
    value: '195950051179',
    market: 'Índia',
    partNumber: 'MD1R4HN/A',
    sources: ['https://inspireonline.in/products/iphone-16e-md1r4hn-a'],
  },
  {
    model: 'iPhone 16e',
    color: 'Preto',
    memory: '256 GB',
    value: '195950051254',
    market: 'Índia',
    partNumber: 'MD1T4HN/A',
    sources: ['https://inspireonline.in/products/iphone-16e-md1t4hn-a'],
  },
  {
    model: 'iPhone 16e',
    color: 'Branco',
    memory: '256 GB',
    value: '195950051339',
    market: 'Índia',
    partNumber: 'MD1W4HN/A',
    sources: ['https://indigo.iplanet.one/products/iphone-16e-md1w4hn-a'],
  },
  {
    model: 'iPhone 16e',
    color: 'Preto',
    memory: '512 GB',
    value: '195950051414',
    market: 'Índia',
    partNumber: 'MD1X4HN/A',
    sources: ['https://iplanet.one/products/iphone-16e-md1x4hn-a'],
  },
  {
    model: 'iPhone 16e',
    color: 'Branco',
    memory: '512 GB',
    value: '195950051490',
    market: 'Índia',
    partNumber: 'MD274HN/A',
    sources: [
      'https://iplanet.one/products/iphone-16e-512gb-white?variant=50741385953589',
    ],
  },
  {
    model: 'iPhone 17e',
    color: 'Preto',
    memory: '256 GB',
    value: '195951030463',
    market: 'Índia',
    partNumber: 'MHRV4HN/A',
    sources: ['https://www.imagineonline.store/products/iphone-17e-mhrv4hn-a'],
  },
  {
    model: 'iPhone 17e',
    color: 'Branco',
    memory: '256 GB',
    value: '195951030654',
    market: 'Índia',
    partNumber: 'MHRW4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17e-mhrw4hn-a'],
  },
  {
    model: 'iPhone 17e',
    color: 'Rosa-pálido',
    memory: '256 GB',
    value: '195951030845',
    market: 'Índia',
    partNumber: 'MHRX4HN/A',
    sources: ['https://inspireonline.in/products/iphone-17e-mhrx4hn-a'],
  },
  {
    model: 'iPhone 17e',
    color: 'Preto',
    memory: '512 GB',
    value: '195951031033',
    market: 'Índia',
    partNumber: 'MHRY4HN/A',
    sources: ['https://iplanet.one/products/iphone-17e-mhry4hn-a'],
  },
  {
    model: 'iPhone 17e',
    color: 'Branco',
    memory: '512 GB',
    value: '195951031224',
    market: 'Índia',
    partNumber: 'MHU04HN/A',
    sources: ['https://iplanet.one/products/iphone-17e-mhu04hn-a'],
  },
  {
    model: 'iPhone 17e',
    color: 'Rosa-pálido',
    memory: '512 GB',
    value: '195951031415',
    market: 'Índia',
    partNumber: 'MHU34HN/A',
    sources: ['https://iplanet.one/products/iphone-17e-mhu34hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Preto-espacial',
    memory: '256 GB',
    value: '195950622522',
    market: 'Índia',
    partNumber: 'MG2L4HN/A',
    sources: ['https://iplanet.one/products/iphone-air-mg2l4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Branco-nuvem',
    memory: '256 GB',
    value: '195950622720',
    market: 'Índia',
    partNumber: 'MG2M4HN/A',
    sources: ['https://inspireonline.in/products/iphone-air-mg2m4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Dourado-claro',
    memory: '256 GB',
    value: '195950622928',
    market: 'Índia',
    partNumber: 'MG2N4HN/A',
    sources: ['https://iplanet.one/products/iphone-air-mg2n4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Azul-céu',
    memory: '256 GB',
    value: '195950623123',
    market: 'Índia',
    partNumber: 'MG2P4HN/A',
    sources: ['https://iplanet.one/products/iphone-air-mg2p4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Preto-espacial',
    memory: '512 GB',
    value: '195950623321',
    market: 'Índia',
    partNumber: 'MG2Q4HN/A',
    sources: ['https://indigo.iplanet.one/products/iphone-air-mg2q4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Branco-nuvem',
    memory: '512 GB',
    value: '195950623529',
    market: 'Índia',
    partNumber: 'MG2T4HN/A',
    sources: ['https://iplanet.one/products/iphone-air-mg2t4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Dourado-claro',
    memory: '512 GB',
    value: '195950623727',
    market: 'Índia',
    partNumber: 'MG2U4HN/A',
    sources: ['https://inspireonline.in/products/iphone-air-mg2u4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Azul-céu',
    memory: '512 GB',
    value: '195950623925',
    market: 'Índia',
    partNumber: 'MG2V4HN/A',
    sources: ['https://iplanet.one/products/iphone-air-mg2v4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Preto-espacial',
    memory: '1 TB',
    value: '195950624120',
    market: 'Índia',
    partNumber: 'MG2W4HN/A',
    sources: ['https://www.imagineonline.store/products/iphone-air-mg2w4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Branco-nuvem',
    memory: '1 TB',
    value: '195950624328',
    market: 'Índia',
    partNumber: 'MG2X4HN/A',
    sources: ['https://iplanet.one/products/iphone-air-mg2x4hn-a'],
  },
  {
    model: 'iPhone Air',
    color: 'Dourado-claro',
    memory: '1 TB',
    value: '195950624526',
    market: 'Índia',
    partNumber: 'MG2Y4HN/A',
    sources: ['https://inspireonline.in/products/iphone-air-mg2y4hn-a'],
  },
  {
    model: 'iPhone 16e',
    color: 'Preto',
    memory: '128 GB',
    value: '195950051865',
    market: 'Brasil',
    partNumber: 'MD1Q4BR/A',
    sources: [
      'https://www.martinsatacado.com.br/produto/smartphone-apple-16e-128gb-preto-md1q4br-a-infostore_TEL2327',
    ],
  },
  {
    model: 'iPhone 16e',
    color: 'Branco',
    memory: '128 GB',
    value: '195950051872',
    market: 'Brasil',
    partNumber: 'MD1R4BR/A',
    sources: [
      'https://www.carrefour.com.br/produto/iphone-16-e-apple-128gb-branco-tela-de-61-5g-e-camera-de-48mp-334083014',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Preto',
    memory: '128 GB',
    value: '195949034701',
    market: 'China continental (CH/A)',
    partNumber: 'MTLD3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtld3ch-a-26469-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Rosa',
    memory: '128 GB',
    value: '195949034725',
    market: 'China continental (CH/A)',
    partNumber: 'MTLE3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtle3ch-a-26467-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Amarelo',
    memory: '128 GB',
    value: '195949034749',
    market: 'China continental (CH/A)',
    partNumber: 'MTLF3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtlf3ch-a-26474-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Azul',
    memory: '128 GB',
    value: '195949034763',
    market: 'China continental (CH/A)',
    partNumber: 'MTLG3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtlg3ch-a-26462-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Verde',
    memory: '128 GB',
    value: '195949034787',
    market: 'China continental (CH/A)',
    partNumber: 'MTLH3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtlh3ch-a-26465-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Preto',
    memory: '256 GB',
    value: '195949034800',
    market: 'China continental (CH/A)',
    partNumber: 'MTLJ3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtlj3ch-a-27006-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Rosa',
    memory: '256 GB',
    value: '195949034824',
    market: 'China continental (CH/A)',
    partNumber: 'MTLK3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtlk3ch-a-27004-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Amarelo',
    memory: '256 GB',
    value: '195949034848',
    market: 'China continental (CH/A)',
    partNumber: 'MTLL3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtll3ch-a-29855-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Azul',
    memory: '256 GB',
    value: '195949034862',
    market: 'China continental (CH/A)',
    partNumber: 'MTLM3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtlm3ch-a-27002-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Verde',
    memory: '256 GB',
    value: '195949034886',
    market: 'China continental (CH/A)',
    partNumber: 'MTLN3CH/A',
    sources: [
      'https://relise.ru/smartfony/smartfony-apple/smartfon-apple-mtln3ch-a-27003-02',
      'https://www.techwalls.com/iphone-15-model-number-a2846-a3089-a3090-a3092-differences/',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Preto',
    memory: '128 GB',
    value: '195949115981',
    market: 'Vendido no Paraguai; pacote importado VC/A (Canadá)',
    partNumber: 'MTMH3VC/A',
    sources: [
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-15-128gb-black-sim-883613',
      'https://www.jumpplus.com/products/iphone-15-mtmh3vc-a',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Azul',
    memory: '128 GB',
    value: '195949036453',
    market: 'Vendido no Paraguai; pacote importado BE/A (América Latina)',
    partNumber: 'MTP43BE/A',
    sources: [
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-15-128gb-blue-sim-883614',
      'https://co.tiendasishop.com/products/iphone-15-mtp43be-a',
    ],
  },
  {
    model: 'iPhone 15',
    color: 'Rosa',
    memory: '256 GB',
    value: '195949037016',
    market: 'Vendido no Paraguai; pacote importado HN/A (Índia)',
    partNumber: 'MTP73HN/A',
    sources: [
      'https://nissei.com/py/apple-iphone-15-a3090-256-gb-pink',
      'https://inspireonline.in/products/iphone-15-mtp73hn-a',
    ],
  },
  {
    model: 'iPhone 16',
    color: 'Preto',
    memory: '128 GB',
    value: '195949821813',
    market: 'Vendido no Paraguai; pacote importado BE/A (América Latina)',
    partNumber: 'MYE73BE/A',
    sources: [
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-16-a3287-128gb-black-sim-948623',
      'https://co.tiendasishop.com/products/iphone-16-mye73be-a',
    ],
  },
  {
    model: 'iPhone 16 Plus',
    color: 'Ultramarino',
    memory: '128 GB',
    value: '195949722707',
    market: 'Vendido no Paraguai; pacote importado HN/A (Índia)',
    partNumber: 'MXVX3HN/A',
    sources: [
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-16-plus-128gb-u-marine-sim-987699',
      'https://iplanet.one/products/iphone-16-plus-128gb-ultramarine',
    ],
  },
  {
    model: 'iPhone 17 Pro',
    color: 'Prateado',
    memory: '256 GB',
    value: '195950627077',
    market: 'Vendido no Paraguai; pacote importado BE/A (América Latina)',
    partNumber: 'MG8G4BE/A',
    sources: [
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-17-pro-256gb-silver-be-a-1062032',
      'https://cr.tiendasishop.com/products/iphone-17-pro-mg8g4be-a',
    ],
  },
  {
    model: 'iPhone 17 Pro Max',
    color: 'Azul-intenso',
    memory: '512 GB',
    value: '195950639728',
    market: 'Vendido no Paraguai; pacote importado BE/A (América Latina)',
    partNumber: 'MFYU4BE/A',
    sources: [
      'https://www.shoppingchina.com.py/producto/celular-apple-iphone-17-pro-max-512gb-deep-blue-be-a-1064617',
      'https://cr.tiendasishop.com/products/iphone-17-pro-mfyu4be-a',
    ],
  },
];
