// Verified 2026-09-20. See docs/catalog-iphone-18.md for scope and sources.
// Codes are transcribed from sources; never inferred from a numeric sequence.
export type Iphone18CatalogCode = {
  model: string;
  color: string;
  memory: string;
  value: string;
  market: string;
  partNumber?: string;
  sources: readonly string[];
};

export const IPHONE_18_CATALOG_CODES: readonly Iphone18CatalogCode[] = [
  {
    model: 'iPhone 18 Pro Max',
    color: 'Preto',
    memory: '256 GB',
    value: '4549995734546',
    market: 'Japão',
    partNumber: 'MJX54J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjx54j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Prateado',
    memory: '256 GB',
    value: '4549995734591',
    market: 'Japão',
    partNumber: 'MJX64J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Bordô',
    memory: '256 GB',
    value: '4549995734645',
    market: 'Japão',
    partNumber: 'MJX74J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjx74j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Glacial',
    memory: '256 GB',
    value: '4549995734690',
    market: 'Japão',
    partNumber: 'MJX84J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjx84j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Preto',
    memory: '512 GB',
    value: '4549995734744',
    market: 'Japão',
    partNumber: 'MJX94J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjx94j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Prateado',
    memory: '512 GB',
    value: '4549995734799',
    market: 'Japão',
    partNumber: 'MJXA4J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjxa4j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Bordô',
    memory: '512 GB',
    value: '4549995734843',
    market: 'Japão',
    partNumber: 'MJXC4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Glacial',
    memory: '512 GB',
    value: '4549995734898',
    market: 'Japão',
    partNumber: 'MJXD4J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjxd4j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Preto',
    memory: '1 TB',
    value: '4549995734942',
    market: 'Japão',
    partNumber: 'MJXE4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Prateado',
    memory: '1 TB',
    value: '4549995734997',
    market: 'Japão',
    partNumber: 'MJXF4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Bordô',
    memory: '1 TB',
    value: '4549995735048',
    market: 'Japão',
    partNumber: 'MJXG4J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjxg4j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Glacial',
    memory: '1 TB',
    value: '4549995735093',
    market: 'Japão',
    partNumber: 'MJXH4J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjxh4j-a'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Preto',
    memory: '2 TB',
    value: '4549995735147',
    market: 'Japão',
    partNumber: 'MJXJ4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Prateado',
    memory: '2 TB',
    value: '4549995735192',
    market: 'Japão',
    partNumber: 'MJXK4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Bordô',
    memory: '2 TB',
    value: '4549995735246',
    market: 'Japão',
    partNumber: 'MJXL4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Glacial',
    memory: '2 TB',
    value: '4549995735291',
    market: 'Japão',
    partNumber: 'MJXM4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Preto',
    memory: '256 GB',
    value: '4549995734140',
    market: 'Japão',
    partNumber: 'MJR54J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjr54j-a'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Prateado',
    memory: '256 GB',
    value: '4549995734157',
    market: 'Japão',
    partNumber: 'MJR64J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjr64j-a'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Bordô',
    memory: '256 GB',
    value: '4549995734164',
    market: 'Japão',
    partNumber: 'MJR74J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjr74j-a'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '256 GB',
    value: '4549995734171',
    market: 'Japão',
    partNumber: 'MJR84J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjr84j-a'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Preto',
    memory: '512 GB',
    value: '4549995734188',
    market: 'Japão',
    partNumber: 'MJR94J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjr94j-a'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Prateado',
    memory: '512 GB',
    value: '4549995734195',
    market: 'Japão',
    partNumber: 'MJRC4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Bordô',
    memory: '512 GB',
    value: '4549995734201',
    market: 'Japão',
    partNumber: 'MJRD4J/A',
    sources: ['https://c-smart.jp/products/iphone-18-pro-mjrd4j-a'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '512 GB',
    value: '4549995734218',
    market: 'Japão',
    partNumber: 'MJRE4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Preto',
    memory: '1 TB',
    value: '4549995734225',
    market: 'Japão',
    partNumber: 'MJRF4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Prateado',
    memory: '1 TB',
    value: '4549995734232',
    market: 'Japão',
    partNumber: 'MJRG4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Bordô',
    memory: '1 TB',
    value: '4549995734249',
    market: 'Japão',
    partNumber: 'MJRH4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '1 TB',
    value: '4549995734256',
    market: 'Japão',
    partNumber: 'MJRJ4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Preto',
    memory: '2 TB',
    value: '4549995734263',
    market: 'Japão',
    partNumber: 'MJRK4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Prateado',
    memory: '2 TB',
    value: '4549995734270',
    market: 'Japão',
    partNumber: 'MJRL4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Bordô',
    memory: '2 TB',
    value: '4549995734287',
    market: 'Japão',
    partNumber: 'MJRM4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '2 TB',
    value: '4549995734294',
    market: 'Japão',
    partNumber: 'MJRN4J/A',
    sources: ['https://greens-one.com/itemnumber-sim/19/'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Prateado',
    memory: '256 GB',
    value: '195951414713',
    market: 'Estados Unidos',
    sources: ['https://www.target.com/p/-/A-1013267434'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Preto',
    memory: '512 GB',
    value: '195951414744',
    market: 'Estados Unidos',
    sources: ['https://www.target.com/p/-/A-1013267439'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Prateado',
    memory: '1 TB',
    value: '195951414799',
    market: 'Estados Unidos',
    sources: ['https://www.target.com/p/-/A-1013267449'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Preto',
    memory: '512 GB',
    value: '195951409108',
    market: 'Estados Unidos',
    sources: ['https://www.target.com/p/-/A-1013267447'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Bordô',
    memory: '512 GB',
    value: '195951409122',
    market: 'Estados Unidos',
    sources: ['https://www.target.com/p/-/A-1013267437'],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Glacial',
    memory: '1 TB',
    value: '195951409177',
    market: 'Estados Unidos',
    sources: ['https://www.target.com/p/-/A-1013267441'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '256 GB',
    value: '0195951416496',
    market: 'Finlândia',
    sources: ['https://www.multitronic.fi/en/products/4630046'],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '256 GB',
    value: '0195951416014',
    market: 'Europa (QL/A)',
    sources: [
      'https://www.neobyte.es/apple-iphone-18-pro-256gb-glacier-smartphone-6-3-43370.html',
    ],
  },
  {
    model: 'iPhone 18 Pro',
    color: 'Glacial',
    memory: '256 GB',
    value: '0195951416656',
    market: 'Polônia (HX/A)',
    sources: [
      'https://lantre.pl/apple-iphone-18-pro-256gb-blekit-lodowca-glacier-mjrt4hx-a.html',
    ],
  },
  {
    model: 'iPhone 18 Pro Max',
    color: 'Prateado',
    memory: '2 TB',
    value: '0195951410630',
    market: 'Europa (ZD/A)',
    sources: [
      'https://www.dustin.be/nl/smartphones/apple/apple-iphone-18-pro-max-smartphone-zilver-2000gb-art-mjy34zd-a-num-191100285/',
    ],
  },
];

export const IPHONE_18_CATALOG_PRODUCTS = [
  'iPhone 18 Pro',
  'iPhone 18 Pro Max',
].flatMap((model) =>
  ['Preto', 'Prateado', 'Glacial', 'Bordô'].flatMap((color) =>
    ['256 GB', '512 GB', '1 TB', '2 TB'].map((memory) => ({
      key: [model, color, memory]
        .map((label) =>
          label
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '')
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, ''),
        )
        .join('-'),
      model,
      color,
      memory,
      codes: IPHONE_18_CATALOG_CODES.filter(
        (code) =>
          code.model === model &&
          code.color === color &&
          code.memory === memory,
      ).map(({ value, market }) => ({ value, market })),
    })),
  ),
);
